id: PACC5C0AE
initial_creation_type: input
source_metadata:
  Title: Dhih Journal Vol 57
  Editor: Losang Dorjee Rabling
  Publisher: Central University of Tibetan Studies
  Place of Publication: Sarnath, Varanasi
  Year: '2017'
  Dvādaśakāranayastotram:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:07:13.423547'
last_modified_at: '2022-03-08T17:07:13.423556'
